#!/bin/bash
# Random 48 bytes / 384 bits
# base64 encoded (64 characters, maximum encoded line length)
# Reduced to non-ambiguous alphanumeric characters
# Reduced into 16 characters
# Eliminate any terminal newline
openssl rand -base64 48 | tr -cd '[:alnum:]' | tr -d '[iIlLjO01]' | cut -c -16 | tr -d '\n' | pbcopy
